<?php

namespace Database\Seeders;

use App\Models\CapaianKinerja;
use Illuminate\Database\Seeder;

class CapaianKinerjaSeeder extends Seeder
{
    public function run(): void
    {
        $samples = [
            // ==================== TRIWULAN 1 ====================
            [
                'tahun' => 2026,
                'triwulan' => 'TW I',
                'sasaran' => 'Meningkatnya Akses dan Kualitas Layanan Pendidikan Anak Usia Dini dan Pendidikan Dasar',
                'indikator' => 'Angka Partisipasi Kasar (APK) PAUD',
                'satuan' => '%',
                'target_tahunan' => 85.50,
                'pagu_anggaran' => 4500000000,
                'target_tw1' => 20.00,
                'target_tw2' => 25.00,
                'target_tw3' => 25.00,
                'target_tw4' => 15.50,
                'realisasi_kinerja' => 21.30,
                'capaian_kinerja_persen' => 106.50,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 950000000,
                'capaian_keuangan_persen' => 21.11,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Laporan_APK_PAUD_TW1_2026.pdf',
                'bukti_file_size' => '1.2 MB',
                'bukti_keterangan' => 'Realisasi TW I melampaui target berkala berkat program sosialisasi PAUD Terpadu.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW I',
                'sasaran' => 'Meningkatnya Pemerataan dan Mutu Pendidikan Jenjang Sekolah Dasar & Menengah Pertama',
                'indikator' => 'Persentase Satuan Pendidikan SD/SMP yang Terakreditasi Minimal B',
                'satuan' => '%',
                'target_tahunan' => 92.00,
                'pagu_anggaran' => 8250000000,
                'target_tw1' => 22.00,
                'target_tw2' => 24.00,
                'target_tw3' => 24.00,
                'target_tw4' => 22.00,
                'realisasi_kinerja' => 22.00,
                'capaian_kinerja_persen' => 100.00,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 1800000000,
                'capaian_keuangan_persen' => 21.82,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'SK_Akreditasi_BAN_PDM_TW1.pdf',
                'bukti_file_size' => '2.4 MB',
                'bukti_keterangan' => 'Pendampingan pra-akreditasi terlaksana pada 18 satuan pendidikan.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW I',
                'sasaran' => 'Peningkatan Kompetensi, Kualifikasi, dan Profesionalisme Tenaga Pendidik',
                'indikator' => 'Jumlah Guru dan Tenaga Kependidikan yang Mengikuti Pelatihan Peningkatan Kompetensi',
                'satuan' => 'Orang',
                'target_tahunan' => 1200.00,
                'pagu_anggaran' => 1850000000,
                'target_tw1' => 250.00,
                'target_tw2' => 400.00,
                'target_tw3' => 350.00,
                'target_tw4' => 200.00,
                'realisasi_kinerja' => 280.00,
                'capaian_kinerja_persen' => 112.00,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 410000000,
                'capaian_keuangan_persen' => 22.16,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Rekap_Sertifikat_Pelatihan_TW1.pdf',
                'bukti_file_size' => '890 KB',
                'bukti_keterangan' => 'Pelatihan Implementasi Kurikulum Merdeka bagi 280 guru terlaksana sesuai jadwal.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW I',
                'sasaran' => 'Penyediaan dan Pemeliharaan Sarana dan Prasarana Satuan Pendidikan yang Memadai',
                'indikator' => 'Jumlah Ruang Kelas Sekolah yang Direhabilitasi dalam Kondisi Baik',
                'satuan' => 'Ruang Kelas',
                'target_tahunan' => 45.00,
                'pagu_anggaran' => 3600000000,
                'target_tw1' => 8.00,
                'target_tw2' => 15.00,
                'target_tw3' => 14.00,
                'target_tw4' => 8.00,
                'realisasi_kinerja' => 7.00,
                'capaian_kinerja_persen' => 87.50,
                'predikat_kinerja' => 'Berhasil',
                'realisasi_keuangan' => 620000000,
                'capaian_keuangan_persen' => 17.22,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'BAST_Rehab_Sekolah_TW1.pdf',
                'bukti_file_size' => '3.1 MB',
                'bukti_keterangan' => '7 ruang kelas rampung 100%, 1 ruang kelas menunggu penyelesaian finishing.',
                'status_bukti' => 'Lengkap',
            ],

            // ==================== TRIWULAN 2 ====================
            [
                'tahun' => 2026,
                'triwulan' => 'TW II',
                'sasaran' => 'Meningkatnya Akses dan Kualitas Layanan Pendidikan Anak Usia Dini dan Pendidikan Dasar',
                'indikator' => 'Angka Partisipasi Kasar (APK) PAUD',
                'satuan' => '%',
                'target_tahunan' => 85.50,
                'pagu_anggaran' => 4500000000,
                'target_tw1' => 20.00,
                'target_tw2' => 25.00,
                'target_tw3' => 25.00,
                'target_tw4' => 15.50,
                'realisasi_kinerja' => 24.80,
                'capaian_kinerja_persen' => 99.20,
                'predikat_kinerja' => 'Berhasil',
                'realisasi_keuangan' => 1250000000,
                'capaian_keuangan_persen' => 27.78,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Laporan_APK_PAUD_TW2_2026.pdf',
                'bukti_file_size' => '1.5 MB',
                'bukti_keterangan' => 'Peningkatan pendaftaran peserta didik baru PAUD di semester genap.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW II',
                'sasaran' => 'Meningkatnya Pemerataan dan Mutu Pendidikan Jenjang Sekolah Dasar & Menengah Pertama',
                'indikator' => 'Persentase Satuan Pendidikan SD/SMP yang Terakreditasi Minimal B',
                'satuan' => '%',
                'target_tahunan' => 92.00,
                'pagu_anggaran' => 8250000000,
                'target_tw1' => 22.00,
                'target_tw2' => 24.00,
                'target_tw3' => 24.00,
                'target_tw4' => 22.00,
                'realisasi_kinerja' => 25.00,
                'capaian_kinerja_persen' => 104.17,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 2100000000,
                'capaian_keuangan_persen' => 25.45,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'SK_Akreditasi_BAN_PDM_TW2.pdf',
                'bukti_file_size' => '2.1 MB',
                'bukti_keterangan' => 'Visitasi akreditasi selesai pada tahap 2 dengan capaian memuaskan.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW II',
                'sasaran' => 'Peningkatan Kompetensi, Kualifikasi, dan Profesionalisme Tenaga Pendidik',
                'indikator' => 'Jumlah Guru dan Tenaga Kependidikan yang Mengikuti Pelatihan Peningkatan Kompetensi',
                'satuan' => 'Orang',
                'target_tahunan' => 1200.00,
                'pagu_anggaran' => 1850000000,
                'target_tw1' => 250.00,
                'target_tw2' => 400.00,
                'target_tw3' => 350.00,
                'target_tw4' => 200.00,
                'realisasi_kinerja' => 395.00,
                'capaian_kinerja_persen' => 98.75,
                'predikat_kinerja' => 'Berhasil',
                'realisasi_keuangan' => 610000000,
                'capaian_keuangan_persen' => 32.97,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Dokumentasi_Bimtek_Guru_TW2.pdf',
                'bukti_file_size' => '1.8 MB',
                'bukti_keterangan' => 'Pelatihan kompetensi digital dan asesmen diagnostik bagi para guru.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW II',
                'sasaran' => 'Penyediaan dan Pemeliharaan Sarana dan Prasarana Satuan Pendidikan yang Memadai',
                'indikator' => 'Jumlah Ruang Kelas Sekolah yang Direhabilitasi dalam Kondisi Baik',
                'satuan' => 'Ruang Kelas',
                'target_tahunan' => 45.00,
                'pagu_anggaran' => 3600000000,
                'target_tw1' => 8.00,
                'target_tw2' => 15.00,
                'target_tw3' => 14.00,
                'target_tw4' => 8.00,
                'realisasi_kinerja' => 15.00,
                'capaian_kinerja_persen' => 100.00,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 1200000000,
                'capaian_keuangan_persen' => 33.33,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Laporan_Progres_Fisik_Rehab_TW2.pdf',
                'bukti_file_size' => '4.2 MB',
                'bukti_keterangan' => 'Seluruh paket rehabilitasi triwulan II telah serah terima sementara (PHO).',
                'status_bukti' => 'Lengkap',
            ],

            // ==================== TRIWULAN 3 ====================
            [
                'tahun' => 2026,
                'triwulan' => 'TW III',
                'sasaran' => 'Meningkatnya Akses dan Kualitas Layanan Pendidikan Anak Usia Dini dan Pendidikan Dasar',
                'indikator' => 'Angka Partisipasi Kasar (APK) PAUD',
                'satuan' => '%',
                'target_tahunan' => 85.50,
                'pagu_anggaran' => 4500000000,
                'target_tw1' => 20.00,
                'target_tw2' => 25.00,
                'target_tw3' => 25.00,
                'target_tw4' => 15.50,
                'realisasi_kinerja' => 25.50,
                'capaian_kinerja_persen' => 102.00,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 1150000000,
                'capaian_keuangan_persen' => 25.56,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Data_Dapodik_PAUD_TW3_2026.pdf',
                'bukti_file_size' => '1.9 MB',
                'bukti_keterangan' => 'Sinkronisasi data Dapodik PAUD semester ganjil T.A 2026/2027.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW III',
                'sasaran' => 'Meningkatnya Pemerataan dan Mutu Pendidikan Jenjang Sekolah Dasar & Menengah Pertama',
                'indikator' => 'Persentase Satuan Pendidikan SD/SMP yang Terakreditasi Minimal B',
                'satuan' => '%',
                'target_tahunan' => 92.00,
                'pagu_anggaran' => 8250000000,
                'target_tw1' => 22.00,
                'target_tw2' => 24.00,
                'target_tw3' => 24.00,
                'target_tw4' => 22.00,
                'realisasi_kinerja' => 23.50,
                'capaian_kinerja_persen' => 97.92,
                'predikat_kinerja' => 'Berhasil',
                'realisasi_keuangan' => 1950000000,
                'capaian_keuangan_persen' => 23.64,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Monitoring_Akreditasi_TW3.pdf',
                'bukti_file_size' => '2.8 MB',
                'bukti_keterangan' => 'Monitoring berkala pemenuhan 8 Standar Nasional Pendidikan.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW III',
                'sasaran' => 'Peningkatan Kompetensi, Kualifikasi, dan Profesionalisme Tenaga Pendidik',
                'indikator' => 'Jumlah Guru dan Tenaga Kependidikan yang Mengikuti Pelatihan Peningkatan Kompetensi',
                'satuan' => 'Orang',
                'target_tahunan' => 1200.00,
                'pagu_anggaran' => 1850000000,
                'target_tw1' => 250.00,
                'target_tw2' => 400.00,
                'target_tw3' => 350.00,
                'target_tw4' => 200.00,
                'realisasi_kinerja' => 360.00,
                'capaian_kinerja_persen' => 102.86,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 540000000,
                'capaian_keuangan_persen' => 29.19,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Daftar_Hadir_Diklat_Guru_TW3.pdf',
                'bukti_file_size' => '1.1 MB',
                'bukti_keterangan' => 'Pelatihan penulisan karya tulis ilmiah dan publikasi bagi guru berprestasi.',
                'status_bukti' => 'Lengkap',
            ],
            [
                'tahun' => 2026,
                'triwulan' => 'TW III',
                'sasaran' => 'Penyediaan dan Pemeliharaan Sarana dan Prasarana Satuan Pendidikan yang Memadai',
                'indikator' => 'Jumlah Ruang Kelas Sekolah yang Direhabilitasi dalam Kondisi Baik',
                'satuan' => 'Ruang Kelas',
                'target_tahunan' => 45.00,
                'pagu_anggaran' => 3600000000,
                'target_tw1' => 8.00,
                'target_tw2' => 15.00,
                'target_tw3' => 14.00,
                'target_tw4' => 8.00,
                'realisasi_kinerja' => 14.00,
                'capaian_kinerja_persen' => 100.00,
                'predikat_kinerja' => 'Sangat Berhasil',
                'realisasi_keuangan' => 1120000000,
                'capaian_keuangan_persen' => 31.11,
                'bukti_link' => 'https://drive.google.com/drive/folders/18XtuS2NgJyn8FBHwF_cw09qM4JuhPy7P?usp=sharing',
                'bukti_file_name' => 'Dokumentasi_Foto_Fisik_Rehab_TW3.pdf',
                'bukti_file_size' => '5.6 MB',
                'bukti_keterangan' => 'Pekerjaan fisik tahap 3 selesai tepat waktu sesuai kontrak.',
                'status_bukti' => 'Lengkap',
            ]
        ];

        foreach ($samples as $sample) {
            CapaianKinerja::create($sample);
        }
    }
}
