<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CapaianKinerja extends Model
{
    protected $table = 'capaian_kinerja';

    protected $fillable = [
        'tahun',
        'triwulan',
        'sasaran',
        'indikator',
        'satuan',
        'target_tahunan',
        'pagu_anggaran',
        'pagu_tw1',
        'pagu_tw2',
        'pagu_tw3',
        'pagu_tw4',
        'target_tw1',
        'target_tw2',
        'target_tw3',
        'target_tw4',
        'realisasi_kinerja',
        'capaian_kinerja_persen',
        'predikat_kinerja',
        'realisasi_kinerja_tw1',
        'capaian_kinerja_tw1',
        'predikat_kinerja_tw1',
        'realisasi_kinerja_tw2',
        'capaian_kinerja_tw2',
        'predikat_kinerja_tw2',
        'realisasi_kinerja_tw3',
        'capaian_kinerja_tw3',
        'predikat_kinerja_tw3',
        'realisasi_kinerja_tw4',
        'capaian_kinerja_tw4',
        'predikat_kinerja_tw4',
        'realisasi_kinerja_total',
        'capaian_kinerja_total',
        'predikat_kinerja_total',
        'realisasi_keuangan',
        'capaian_keuangan_persen',
        'realisasi_keuangan_tw1',
        'capaian_keuangan_tw1',
        'realisasi_keuangan_tw2',
        'capaian_keuangan_tw2',
        'realisasi_keuangan_tw3',
        'capaian_keuangan_tw3',
        'realisasi_keuangan_tw4',
        'capaian_keuangan_tw4',
        'realisasi_keuangan_total',
        'capaian_keuangan_total',
        'target_rpjmd_kinerja',
        'target_rpjmd_keuangan',
        'capaian_renstra_kinerja',
        'capaian_renstra_keuangan',
        'bukti_link',
        'bukti_file_path',
        'bukti_file_name',
        'bukti_file_size',
        'bukti_keterangan',
        'status_bukti',
        'created_by',
    ];

    protected $casts = [
        'tahun' => 'integer',
        'target_tahunan' => 'float',
        'pagu_anggaran' => 'float',
        'pagu_tw1' => 'float',
        'pagu_tw2' => 'float',
        'pagu_tw3' => 'float',
        'pagu_tw4' => 'float',
        'target_tw1' => 'float',
        'target_tw2' => 'float',
        'target_tw3' => 'float',
        'target_tw4' => 'float',
        'realisasi_kinerja' => 'float',
        'capaian_kinerja_persen' => 'float',
        'realisasi_kinerja_tw1' => 'float',
        'capaian_kinerja_tw1' => 'float',
        'realisasi_kinerja_tw2' => 'float',
        'capaian_kinerja_tw2' => 'float',
        'realisasi_kinerja_tw3' => 'float',
        'capaian_kinerja_tw3' => 'float',
        'realisasi_kinerja_tw4' => 'float',
        'capaian_kinerja_tw4' => 'float',
        'realisasi_kinerja_total' => 'float',
        'capaian_kinerja_total' => 'float',
        'realisasi_keuangan' => 'float',
        'capaian_keuangan_persen' => 'float',
        'realisasi_keuangan_tw1' => 'float',
        'capaian_keuangan_tw1' => 'float',
        'realisasi_keuangan_tw2' => 'float',
        'capaian_keuangan_tw2' => 'float',
        'realisasi_keuangan_tw3' => 'float',
        'capaian_keuangan_tw3' => 'float',
        'realisasi_keuangan_tw4' => 'float',
        'capaian_keuangan_tw4' => 'float',
        'realisasi_keuangan_total' => 'float',
        'capaian_keuangan_total' => 'float',
        'target_rpjmd_kinerja' => 'float',
        'target_rpjmd_keuangan' => 'float',
        'capaian_renstra_kinerja' => 'float',
        'capaian_renstra_keuangan' => 'float',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'created_by');
    }
}
